# Generated by Django 3.2.11 on 2022-07-02 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dispatch_data_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 22, 49, 55, 533363)),
        ),
    ]
