# Generated by Django 3.2.7 on 2022-07-13 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dispatch_data_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispacthPostUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 13, 13, 45, 9, 875161)),
        ),
    ]
