# Generated by Django 3.2.7 on 2022-07-19 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220713_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch_data',
            name='Label_qty',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 14, 36, 6, 7530)),
        ),
    ]
