# Generated by Django 3.2.7 on 2022-07-22 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220719_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispacthpostuser',
            name='mac_id',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 21, 30, 58, 355508)),
        ),
    ]
