# Generated by Django 3.2.11 on 2022-08-08 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220722_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_id', models.CharField(blank=True, default='', max_length=18)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 4, 55, 428212))),
            ],
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_type', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dispacthpostuser',
            name='user_password',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 4, 55, 428212)),
        ),
        migrations.AddField(
            model_name='dispacthpostuser',
            name='store_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.storetype'),
        ),
    ]
