# Generated by Django 3.2.7 on 2022-08-06 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220722_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispacthpostuser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dispacthpostuser',
            name='store_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 19, 56, 17, 624)),
        ),
    ]
