# Generated by Django 3.2.11 on 2022-08-08 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220808_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispacthpostuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=15),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 29, 40, 126264)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 12, 29, 40, 141884)),
        ),
    ]
