# Generated by Django 3.2.4 on 2022-08-30 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220830_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispacthpostuser',
            name='mac_id',
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 11, 50, 53, 642886)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 11, 50, 53, 644788)),
        ),
    ]
