# Generated by Django 3.2.4 on 2022-08-30 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220830_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispacthpostuser',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='dispacthpostuser',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 12, 14, 1, 718180)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 30, 12, 14, 1, 736840)),
        ),
    ]
