# Generated by Django 3.2.4 on 2022-09-02 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220830_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 17, 13, 25, 277928)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 17, 13, 25, 280923)),
        ),
        migrations.CreateModel(
            name='DispatchNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distpatch_no', models.CharField(blank=True, max_length=11)),
                ('status', models.BooleanField(default=False)),
                ('store', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.storetype')),
            ],
        ),
    ]
