# Generated by Django 3.2.4 on 2022-09-05 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220902_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='Packing_no',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 13, 17, 43, 414344)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 13, 17, 43, 417339)),
        ),
    ]
