# Generated by Django 3.2.7 on 2022-09-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220806_1956'),
        ('api', '0016_auto_20220905_1317'),
    ]

    operations = [
    ]
