# Generated by Django 3.2.7 on 2022-09-27 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_0007_auto_20220806_1956_0016_auto_20220905_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleNumber', models.CharField(blank=True, default='', max_length=18)),
                ('storeName', models.CharField(blank=True, default='', max_length=18)),
                ('salesCreatedDate', models.DateTimeField(default=datetime.datetime(2022, 9, 27, 23, 32, 39, 590713))),
                ('saleTotal', models.CharField(blank=True, default='', max_length=20)),
                ('saleDiscount', models.CharField(blank=True, default='', max_length=20)),
                ('saleCard', models.CharField(blank=True, default='', max_length=20)),
                ('saleCash', models.CharField(blank=True, default='', max_length=20)),
                ('salePoints', models.CharField(blank=True, default='', max_length=20)),
                ('saleBalance', models.CharField(blank=True, default='', max_length=20)),
                ('uniqueNumber', models.CharField(blank=True, default='', max_length=8)),
                ('rowQty', models.CharField(blank=True, default='', max_length=20)),
                ('rowTotal', models.CharField(blank=True, default='', max_length=20)),
                ('rowRate', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='dispacthpostuser',
            name='store_type',
        ),
        migrations.AlterField(
            model_name='dispacthpostuser',
            name='password',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 23, 32, 39, 589685)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 23, 32, 39, 590713)),
        ),
    ]
