# Generated by Django 3.2.7 on 2022-10-13 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20221013_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledata',
            name='isNotExchange',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 0, 39, 33, 498064)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 0, 39, 33, 499061)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 14, 0, 39, 33, 499061)),
        ),
    ]
