# Generated by Django 3.2.7 on 2022-10-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20221012_1023'),
        ('api', '0021_auto_20221014_0039'),
    ]

    operations = [
    ]
