# Generated by Django 3.2.7 on 2022-10-31 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_0020_auto_20221012_1023_0021_auto_20221014_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 10, 14, 33, 308004)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 10, 14, 33, 308626)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='mac_id',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 10, 14, 33, 308918)),
        ),
    ]
