# Generated by Django 3.2.7 on 2022-11-02 19:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_0020_auto_20221012_1023_0021_auto_20221014_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 0, 36, 42, 900443)),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='distpatch_no',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dispatchnumber'),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 0, 36, 42, 901471)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='mac_id',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 0, 36, 42, 901471)),
        ),
    ]
