# Generated by Django 3.2.7 on 2022-11-02 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20221103_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 0, 55, 18, 466684)),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='distpatch_no',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dispatchnumber'),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 0, 55, 18, 466684)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 0, 55, 18, 466684)),
        ),
    ]
