# Generated by Django 3.2.7 on 2022-11-04 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20221103_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 16, 5, 216213)),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='distpatch_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 16, 5, 216213)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 16, 5, 216213)),
        ),
    ]
