# Generated by Django 3.2.7 on 2022-11-04 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20221104_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 46, 49, 203983)),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='distpatch_no',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dispatchnumber'),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 46, 49, 206976)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 11, 46, 49, 207971)),
        ),
    ]
