# Generated by Django 3.2.7 on 2022-12-27 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20221104_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueNumber', models.CharField(blank=True, default='', max_length=8)),
                ('headline', models.CharField(blank=True, default='', max_length=18)),
                ('updatedPrice', models.CharField(blank=True, default=0, max_length=8, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 23, 3, 57, 951741)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 23, 3, 57, 951741)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 23, 3, 57, 951741)),
        ),
    ]
