# Generated by Django 3.2.7 on 2022-11-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20221031_1014'),
        ('api', '0026_auto_20221104_1146'),
    ]

    operations = [
    ]
