# Generated by Django 3.2.7 on 2022-12-27 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20221227_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 0, 6, 31, 513837)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 0, 6, 31, 513837)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 0, 6, 31, 513837)),
        ),
        migrations.AlterField(
            model_name='updatedprice',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
