# Generated by Django 3.2.7 on 2022-12-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_merge_0023_auto_20221031_1014_0026_auto_20221104_1146'),
        ('api', '0028_auto_20221228_0006'),
    ]

    operations = [
    ]
