# Generated by Django 3.2.7 on 2023-05-29 14:40

import api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20221228_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 10, 53, 51963)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 10, 53, 52964)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 10, 53, 53961)),
        ),
        migrations.CreateModel(
            name='StaticBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_no', models.CharField(default=api.models.StaticBarcode.check_inward_no, editable=False, max_length=8, unique=True)),
                ('product_name', models.CharField(max_length=30)),
                ('product_initials', models.CharField(max_length=5)),
                ('count', models.IntegerField(default=0)),
                ('dispatch_no', models.ForeignKey(blank=True, default='DISP1888888', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dispatchnumber')),
            ],
        ),
    ]
