# Generated by Django 3.2.7 on 2023-05-29 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20230529_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 30, 47, 815601)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 30, 47, 817643)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 30, 47, 817643)),
        ),
        migrations.AlterField(
            model_name='staticbarcode',
            name='product_initials',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='staticbarcode',
            name='product_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
