# Generated by Django 3.2.7 on 2023-05-29 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20230529_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 37, 22, 647996)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 37, 22, 650000)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 20, 37, 22, 650000)),
        ),
        migrations.AlterField(
            model_name='staticbarcode',
            name='dispatch_no',
            field=models.CharField(default='DISP1888888', editable=False, max_length=14),
        ),
    ]
