# Generated by Django 3.2.7 on 2023-09-24 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20230925_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='Exception_quantity',
            field=models.FloatField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 1, 22, 12, 192079)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 1, 22, 12, 194117)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 1, 22, 12, 194117)),
        ),
    ]
