# Generated by Django 3.2.7 on 2023-09-28 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20230925_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='Exception_quantity',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 0, 35, 51, 701665)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 0, 35, 51, 702665)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 0, 35, 51, 702665)),
        ),
    ]
