# Generated by Django 3.2.7 on 2023-09-28 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20230929_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch_data',
            name='Exception_quantity',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 0, 37, 15, 869091)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 0, 37, 15, 870664)),
        ),
        migrations.AlterField(
            model_name='saledata',
            name='salesCreatedDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 29, 0, 37, 15, 870664)),
        ),
    ]
