# Generated by Django 2.2.28 on 2024-01-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20240102_1059'),
        ('api', '0062_auto_20231229_2057'),
    ]

    operations = [
    ]
