# Generated by Django 3.2.7 on 2024-01-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20240110_1232'),
        ('api', '0075_auto_20240110_2253'),
    ]

    operations = [
    ]
