# Generated by Django 5.0.1 on 2024-01-20 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_dispatch_data_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 17, 0, 38, 583514)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 17, 0, 38, 584513)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 17, 0, 38, 586525)),
        ),
        migrations.AlterField(
            model_name='updatedprice',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
