# Generated by Django 5.0.1 on 2024-01-24 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_alter_dispatch_data_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='supplier_name',
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 10, 55, 34, 982136)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 10, 55, 34, 982136)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 10, 55, 34, 997757)),
        ),
    ]
