# Generated by Django 5.0.1 on 2024-02-01 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_remove_sale_supplier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledata',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 15, 23, 1, 265403)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 15, 23, 1, 267330)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 15, 23, 1, 267330)),
        ),
    ]
