# Generated by Django 5.0.1 on 2024-02-01 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_sale_supplier_alter_dispatch_data_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledata',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 15, 40, 18, 415750)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 15, 40, 18, 419740)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 15, 40, 18, 431121)),
        ),
    ]
