# Generated by Django 5.0.1 on 2024-02-02 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_storetype_logo_alter_dispatch_data_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storetype',
            name='logo',
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 15, 46, 33, 356808)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 15, 46, 33, 356808)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 15, 46, 33, 372424)),
        ),
    ]
