# Generated by Django 3.2.7 on 2024-02-07 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20240208_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledata',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='dispatch_data',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 0, 30, 30, 627429)),
        ),
        migrations.AlterField(
            model_name='maciddata',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 0, 30, 30, 627429)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sup_created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 0, 30, 30, 642488)),
        ),
    ]
