# Generated by Django 3.2.7 on 2024-01-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20240102_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(blank=True, default='', max_length=10)),
                ('discount_value', models.CharField(blank=True, default='', max_length=4)),
                ('discount_class', models.CharField(blank=True, default='', max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='itemwithoutlabel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
