# Generated by Django 3.2.7 on 2024-01-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20240104_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdiscount',
            name='position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
