# Generated by Django 5.0.1 on 2024-01-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20240111_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwithoutlabel',
            name='default_qty',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
