# Generated by Django 5.0.1 on 2024-02-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_itemwithoutlabel_default_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwithoutlabel',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
